networks:
  rustdesk-net1:
    external: false
  rustdesk-net2:
    external: false
  rustdesk-net3:
    external: false

services:
  hbbs1:
    container_name: hbbs1
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r yourdomain1.com:21117 -k _
    volumes:
      - ./data1:/root
    networks:
      - rustdesk-net1
    depends_on:
      - hbbr1
    restart: unless-stopped

  hbbr1:
    container_name: hbbr1
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data1:/root
    networks:
      - rustdesk-net1
    restart: unless-stopped

  hbbs2:
    container_name: hbbs2
    ports:
      - 21125:21115
      - 21126:21116
      - 21126:21116/udp
      - 21128:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r yourdomain2.com:21127 -k _
    volumes:
      - ./data2:/root
    networks:
      - rustdesk-net2
    depends_on:
      - hbbr2
    restart: unless-stopped

  hbbr2:
    container_name: hbbr2
    ports:
      - 21127:21117
      - 21129:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data2:/root
    networks:
      - rustdesk-net2
    restart: unless-stopped

  hbbs3:
    container_name: hbbs3
    ports:
      - 21135:21115
      - 21136:21116
      - 21136:21116/udp
      - 21138:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r yourdomain3.com:21137 -k _
    volumes:
      - ./data3:/root
    networks:
      - rustdesk-net3
    depends_on:
      - hbbr3
    restart: unless-stopped

  hbbr3:
    container_name: hbbr3
    ports:
      - 21137:21117
      - 21139:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./data3:/root
    networks:
      - rustdesk-net3
    restart: unless-stopped
